name: Testes Automatizados

# Evento manual via GitHub Actions UI
on:
  push:
    branches:
        - main

jobs:
  build:
    # Ambiente de execução (última versão do Ubuntu)
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v2

      # Passo 2: Configurar Node.js
      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Passo 3: Instalar dependências do projeto
      - name: Instalar dependências
        run: npm install

      # Passo 4: Executar testes automatizados
      - name: Executar testes
        run: npm test
